# Generated by Django 5.1.4 on 2026-08-26 11:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notif_type', models.CharField(choices=[('BUDGET_THRESHOLD_80', '80% of category allocation reached'), ('BUDGET_EXCEEDED', 'Category allocation exceeded'), ('PRICE_DROP', 'Price drop on a watched product'), ('SYSTEM', 'System message')], max_length=30)),
                ('message', models.TextField()),
                ('channel', models.CharField(choices=[('EMAIL', 'Email'), ('PUSH', 'Web Push')], max_length=10)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='accounts.studentprofile')),
            ],
            options={
                'db_table': 'notification',
                'indexes': [models.Index(fields=['is_read'], name='notificatio_is_read_8a483f_idx'), models.Index(fields=['created_at'], name='notificatio_created_db7ad3_idx')],
            },
        ),
    ]
