# Generated by Django 5.1.4 on 2026-09-18 08:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_popia_consent_at'),
        ('notifications', '0002_notification_related_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('subscription_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('endpoint', models.URLField(max_length=500)),
                ('p256dh', models.CharField(max_length=255)),
                ('auth', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to='accounts.studentprofile')),
            ],
            options={
                'db_table': 'push_subscription',
                'constraints': [models.UniqueConstraint(fields=('profile', 'endpoint'), name='one_subscription_per_profile_per_endpoint')],
            },
        ),
    ]
