# Generated by Django 5.1.4 on 2026-09-18 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_popia_consent_at'),
        ('budgets', '0001_initial'),
        ('catalog', '0003_cartitem'),
        ('notifications', '0003_pushsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='related_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='catalog.product'),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(condition=models.Q(('is_read', False), ('related_product__isnull', False)), fields=('profile', 'related_product', 'notif_type'), name='one_active_price_drop_notification_per_product'),
        ),
    ]
