# Generated by Django 5.1.4 on 2026-08-26 11:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('preference_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pref_type', models.CharField(max_length=40)),
                ('pref_value', models.CharField(max_length=120)),
                ('radius_km', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='accounts.studentprofile')),
            ],
            options={
                'db_table': 'preference',
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('recommendation_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rank_position', models.PositiveSmallIntegerField()),
                ('was_accepted', models.BooleanField(blank=True, null=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='catalog.product')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='accounts.studentprofile')),
            ],
            options={
                'db_table': 'recommendation',
                'indexes': [models.Index(fields=['issued_at'], name='recommendat_issued__6f0d9e_idx')],
            },
        ),
    ]
