# Generated by Django 5.1.4 on 2026-08-26 11:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Retailer',
            fields=[
                ('retailer_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('integration_type', models.CharField(choices=[('API', 'Official API'), ('SCRAPER', 'Scheduled scraper (where permitted by terms of use)')], max_length=10)),
                ('base_url', models.URLField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'retailer',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(max_length=80)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'product',
                'indexes': [models.Index(fields=['category'], name='product_categor_4f5ce7_idx')],
            },
        ),
        migrations.CreateModel(
            name='PriceRecord',
            fields=[
                ('price_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('delivery_cost', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('retrieved_at', models.DateTimeField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_records', to='catalog.product')),
                ('retailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_records', to='catalog.retailer')),
            ],
            options={
                'db_table': 'price_record',
                'indexes': [models.Index(fields=['price'], name='price_recor_price_dca935_idx'), models.Index(fields=['retrieved_at'], name='price_recor_retriev_f84d6a_idx')],
                'constraints': [models.UniqueConstraint(fields=('product', 'retailer', 'retrieved_at'), name='unique_price_snapshot'), models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='price_non_negative'), models.CheckConstraint(condition=models.Q(('delivery_cost__gte', 0)), name='delivery_cost_non_negative')],
            },
        ),
    ]
