# Generated by Django 5.1.4 on 2026-09-02 10:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('catalog', '0002_retailer_latitude_retailer_longitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('cart_item_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('delivery_cost', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='catalog.product')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='accounts.studentprofile')),
                ('retailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='catalog.retailer')),
            ],
            options={
                'db_table': 'cart_item',
                'constraints': [models.UniqueConstraint(fields=('profile', 'product', 'retailer'), name='one_cart_line_per_product_per_retailer'), models.CheckConstraint(condition=models.Q(('quantity__gte', 1)), name='cart_quantity_at_least_one')],
            },
        ),
    ]
