# Generated by Django 5.1.4 on 2026-09-04 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='popia_consent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
